- name: Play1
  hosts: web
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: "Play1 : Ansible is Configuration Management tool !!"

- name: Play2
  hosts: local
  connection: local
  tasks:
  - name: Ping
    ansible.builtin.ping:

  - name: Print message
    ansible.builtin.debug:
      msg: "Play2: Hello World !!"
