- name: Print username and password
  hosts: web
  vars_prompt:
  - username:
    prompt: Enter your username
    private: false 

  - password:
    prompt: Enter you password
    private: true
  
  tasks:
  - name: Print entered credentails
    ansible.builtin.debug:
      msg: "Enetered username: {{username}}, Entered password: {{password}}"