- name: Install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install
    ansible.builtin.package:
      name: "{{item}}"
      state: present 
    loop:
    - nginx
    - mysql
    - nodejs