- name: Filters usage
  hosts: local
  connection: local
  vars:
    Skills: Linux,Ansible,Shell,K8s,Docker
    currentDesignation: "Senior System Engineer"
    myIp: 172.11.64.22
    Address:
      Flat: 4E
      Appartment: Ramaniyam
      city: Chennai
    workedAs:
      [
      { "key": "Nokia", "value": "Solution Engineer" },
      { "key": "Infinite", "value": "Senior System Engineer" } ]
  tasks:
  - name: Greeting
    ansible.builtin.debug:
      msg: "Hi there!,{{ GREETING | default('How are you') }} "

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ Skills | split (',')}}"
  
  - name: Convert Map to list
    ansible.builtin.debug:
      msg: "{{ Address | dict2items }}"

  - name:  Convert List to Map
    ansible.builtin.debug:
      msg: "{{ workedAs | items2dict }}" 

  - name: ready students yaml
    ansible.builtin.set_fact:
      student_yaml : "{{ lookup ('file', 'student.yaml') | from_yaml }}"
  
  - name: Convert yaml to json
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json }}"
