- name: Filters usage
  hosts: local
  connection: local
  vars:
    Skills: Linux,Ansible,Shell,K8s,Docker
    Designation: "Senior System Engineer"
    myIp: 172.11.64.22
    Address:
      Flat: 4E
      Appartment: Ramaniyam
      city: Chennai
    Friends:
      [
      { "key": "Name", "value": "param" },
      { "key": "Name", "value": "Mani" },
      { "key": "Name", "value": "Poojitha" },
      { "key": "Name", "value": "Jagadeesh" },
      { "key": "Name", "value": "Jai" } ]
  tasks:
  - name: Greeting
    ansible.builtin.debug:
      msg: "Hi there!,{{ GREETING | default('How are you') }} "

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ Skills | split (',')}}"
  
  - name: Convert Map to list
    ansible.builtin.debug:
      msg: "{{ Address | dict2items }}"

  - name:  Convert List to Map
    ansible.builtin.debug:
      msg: "{{ Friends | items2dict }}" 