- name: Idempotent
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: user add
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      state: present
      system: true
    register: print_output

  - name: print response
    ansible.builtin.debug:
      msg: "{{ print_output }}"